name: Collect

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  collect:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm ci
    - id: collect
      run: |
        echo "current_date=$(npm run collect -- ${{ secrets.OPENWEATERHMAP_API_KEY }} 48.5428 16.7606 zistersdorf | grep "Write data for" | cut -c 16-31)" >> $GITHUB_ENV

    - name: Commit changes to repository
      uses: EndBug/add-and-commit@v7
      with:
        add: 'data'
        default_author: github_actions
        message: 'chore: add measurment data of "${{ env.current_date }}"'
